locals {
  common_tags = merge(
    {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    },
    var.tags,
  )
}

# ------------------------------------------------------------------------------
# Security Group
# ------------------------------------------------------------------------------

resource "aws_security_group" "redis" {
  name        = "${var.project_name}-${var.environment}-redis"
  description = "Security group for ElastiCache Redis"
  vpc_id      = var.vpc_id

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-redis-sg"
  })
}

resource "aws_security_group_rule" "redis_from_amplify_ssr" {
  type                     = "ingress"
  from_port                = 6379
  to_port                  = 6379
  protocol                 = "tcp"
  security_group_id        = aws_security_group.redis.id
  source_security_group_id = var.amplify_ssr_security_group_id
  description              = "Allow ingress from Amplify SSR on port 6379"
}

# ------------------------------------------------------------------------------
# Auth Token
# ElastiCache Serverless requires an auth token when transit encryption is
# enabled. Generated by Terraform and composed into REDIS_URL by the secrets
# module as: rediss://:TOKEN@endpoint:6379
# ------------------------------------------------------------------------------

resource "random_password" "auth_token" {
  length           = 64
  special          = true
  override_special = "!&#$^<>-"
}

# ------------------------------------------------------------------------------
# Subnet Group
# ------------------------------------------------------------------------------

resource "aws_elasticache_subnet_group" "main" {
  name       = "${var.project_name}-${var.environment}"
  subnet_ids = var.private_subnet_ids

  tags = local.common_tags
}

# ------------------------------------------------------------------------------
# ElastiCache Serverless (Redis)
# ------------------------------------------------------------------------------

resource "aws_elasticache_serverless_cache" "main" {
  engine = "redis"
  name   = "${var.project_name}-${var.environment}"

  subnet_ids         = var.private_subnet_ids
  security_group_ids = [aws_security_group.redis.id]

  snapshot_retention_limit = var.snapshot_retention_limit

  user_group_id = aws_elasticache_user_group.main.user_group_id

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-redis"
  })
}

# ------------------------------------------------------------------------------
# User / User Group for AUTH
# ElastiCache Serverless uses user groups for access control rather than
# the legacy auth-token parameter. The built-in "default" user is
# automatically included by AWS. We only manage the "app" user.
# ------------------------------------------------------------------------------

resource "aws_elasticache_user" "app" {
  user_id       = "${var.project_name}-${var.environment}-app"
  user_name     = "${var.project_name}-app"
  access_string = "on ~* +@all"
  engine        = "redis"

  authentication_mode {
    type      = "password"
    passwords = [random_password.auth_token.result]
  }

  tags = local.common_tags
}

resource "aws_elasticache_user_group" "main" {
  engine        = "redis"
  user_group_id = "${var.project_name}-${var.environment}"
  user_ids      = [aws_elasticache_user.app.user_id]

  tags = local.common_tags
}
