locals {
  common_tags = merge(
    {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    },
    var.tags,
  )
}

# ------------------------------------------------------------------------------
# Security Group
# ------------------------------------------------------------------------------

resource "aws_security_group" "rds" {
  name        = "${var.project_name}-${var.environment}-rds"
  description = "Security group for RDS Aurora"
  vpc_id      = var.vpc_id

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-rds-sg"
  })
}

resource "aws_security_group_rule" "rds_from_amplify_ssr" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = var.amplify_ssr_security_group_id
  description              = "Allow ingress from Amplify SSR on port 5432"
}

# ------------------------------------------------------------------------------
# DB Subnet Group
# ------------------------------------------------------------------------------

resource "aws_db_subnet_group" "main" {
  name       = "${var.project_name}-${var.environment}"
  subnet_ids = var.private_subnet_ids

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-db-subnet-group"
  })
}

# ------------------------------------------------------------------------------
# Cluster Parameter Group — enforce SSL connections
# ------------------------------------------------------------------------------

resource "aws_rds_cluster_parameter_group" "main" {
  name   = "${var.project_name}-${var.environment}-aurora-pg16"
  family = "aurora-postgresql16"

  parameter {
    name         = "rds.force_ssl"
    value        = "1"
    apply_method = "pending-reboot"
  }

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-cluster-pg"
  })
}

# ------------------------------------------------------------------------------
# Master Password
# Generated by Terraform, stored in Secrets Manager as part of the full
# DATABASE_URL connection string by the secrets module. Rotation is a manual
# operation: update the password, update the secret, redeploy the app.
# ------------------------------------------------------------------------------

resource "random_password" "master" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# ------------------------------------------------------------------------------
# Aurora Serverless v2 Cluster
# ------------------------------------------------------------------------------

resource "aws_rds_cluster" "main" {
  cluster_identifier = "${var.project_name}-${var.environment}"
  engine             = "aurora-postgresql"
  engine_mode        = "provisioned"
  engine_version     = var.engine_version
  database_name      = var.database_name
  master_username    = var.master_username
  master_password    = random_password.master.result

  db_subnet_group_name            = aws_db_subnet_group.main.name
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.main.name
  vpc_security_group_ids          = [aws_security_group.rds.id]

  serverlessv2_scaling_configuration {
    min_capacity = var.min_capacity
    max_capacity = var.max_capacity
  }

  storage_encrypted = true
  # Uses default aws/rds KMS key

  backup_retention_period   = var.backup_retention_period
  preferred_backup_window   = "03:00-04:00"
  copy_tags_to_snapshot     = true
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.environment != "prod"
  final_snapshot_identifier = var.environment == "prod" ? "${var.project_name}-${var.environment}-final" : null

  enabled_cloudwatch_logs_exports = ["postgresql"]

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-aurora-cluster"
  })
}

# ------------------------------------------------------------------------------
# Aurora Serverless v2 Instance
# ------------------------------------------------------------------------------

resource "aws_rds_cluster_instance" "main" {
  identifier         = "${var.project_name}-${var.environment}-1"
  cluster_identifier = aws_rds_cluster.main.id
  instance_class     = "db.serverless"
  engine             = aws_rds_cluster.main.engine
  engine_version     = aws_rds_cluster.main.engine_version

  publicly_accessible          = false
  performance_insights_enabled = var.enable_performance_insights

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-aurora-instance-1"
  })
}

