# Reset Password Flow Contract

openapi: 3.0.3
info:
  title: Reset Password Flow
  description: |
    Contract for the password reset flow. This feature uses Next.js App Router 
    pages and server actions rather than traditional REST endpoints.
  version: 1.0.0

# Note: This is a page-based flow, not a traditional API.
# The contract documents the expected behavior and state transitions.

paths:
  /reset-password:
    get:
      summary: Reset Password Page
      description: |
        Server-rendered page that handles password reset flow.
        
        **Flow Logic**:
        1. If `code` parameter present: Exchange for session
        2. If no code: Check for existing authenticated session
        3. Render appropriate state based on result
      parameters:
        - name: code
          in: query
          description: PKCE authorization code from password reset email
          required: false
          schema:
            type: string
            example: "sb-xxx-auth-code-example-000"
      responses:
        '200':
          description: Page rendered successfully
          content:
            text/html:
              schema:
                type: string
              examples:
                form:
                  summary: Password reset form (valid session)
                  description: |
                    Rendered when:
                    - Code successfully exchanged for session, OR
                    - User already has authenticated session
                invalid_code:
                  summary: Invalid code error
                  description: |
                    Rendered when code exchange fails with invalid code.
                    Shows error message with link to request new reset email.
                expired_code:
                  summary: Expired code error
                  description: |
                    Rendered when code exchange fails due to expiration.
                    Shows error message with link to request new reset email.
                access_denied:
                  summary: Access denied error
                  description: |
                    Rendered when no code provided and no authenticated session.
                    Shows error message with link to request new reset email.

# Server Action Contracts (invoked via form submission)
components:
  schemas:
    PasswordUpdateRequest:
      type: object
      required:
        - password
        - confirmPassword
      properties:
        password:
          type: string
          format: password
          minLength: 12
          description: |
            New password. Must meet complexity requirements:
            - At least 12 characters
            - At least 1 uppercase letter
            - At least 1 lowercase letter
            - At least 1 number
            - At least 1 special character
        confirmPassword:
          type: string
          format: password
          description: Must match password field

    ActionState:
      type: object
      properties:
        data:
          oneOf:
            - type: "null"
            - $ref: '#/components/schemas/PasswordUpdateSuccessData'
        error:
          oneOf:
            - type: "null"
            - type: string
        fieldErrors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        isSuccess:
          type: boolean
        isPending:
          type: boolean

    PasswordUpdateSuccessData:
      type: object
      properties:
        message:
          type: string
          example: "Password updated successfully"
        redirectTo:
          type: string
          example: "/login"

# State Machine Documentation
x-state-machine:
  initial: PAGE_LOAD
  states:
    PAGE_LOAD:
      description: Initial page load
      transitions:
        - to: CODE_EXCHANGE
          condition: code parameter present
        - to: SESSION_CHECK
          condition: no code parameter
    
    CODE_EXCHANGE:
      description: Exchanging code for session via Supabase
      transitions:
        - to: FORM_DISPLAY
          condition: exchange successful
        - to: ERROR_EXPIRED
          condition: code expired
        - to: ERROR_INVALID
          condition: code invalid or already used
    
    SESSION_CHECK:
      description: Checking for existing authenticated session
      transitions:
        - to: FORM_DISPLAY
          condition: session exists
        - to: ERROR_ACCESS_DENIED
          condition: no session
    
    FORM_DISPLAY:
      description: Password reset form displayed
      transitions:
        - to: FORM_VALIDATING
          condition: form submitted
    
    FORM_VALIDATING:
      description: Server action processing form
      transitions:
        - to: SUCCESS
          condition: password updated
        - to: ERROR_VALIDATION
          condition: validation failed
        - to: ERROR_SESSION_EXPIRED
          condition: session expired during form fill
    
    SUCCESS:
      description: Password updated, user signed out
      final: true
      sideEffects:
        - Sign out user
        - Redirect to /login
    
    ERROR_EXPIRED:
      description: Reset code expired
      recovery: Link to /forgot-password
    
    ERROR_INVALID:
      description: Reset code invalid
      recovery: Link to /forgot-password
    
    ERROR_ACCESS_DENIED:
      description: No code and no session
      recovery: Link to /forgot-password
    
    ERROR_VALIDATION:
      description: Form validation errors
      recovery: Fix errors and resubmit
    
    ERROR_SESSION_EXPIRED:
      description: Session expired during form fill
      recovery: Request new reset email

# Error Codes
x-error-codes:
  EXPIRED_CODE:
    message: "This password reset link has expired. Please request a new one."
    userAction: Navigate to /forgot-password
  
  INVALID_CODE:
    message: "This password reset link is invalid or has already been used."
    userAction: Navigate to /forgot-password
  
  ACCESS_DENIED:
    message: "You must use a valid reset link to access this page."
    userAction: Navigate to /forgot-password
  
  SESSION_EXPIRED:
    message: "Your session has expired. Please request a new reset link."
    userAction: Navigate to /forgot-password
  
  VALIDATION_ERROR:
    message: Field-specific validation errors
    userAction: Fix errors and resubmit form
